vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.opt.clipboard = 'unnamedplus'
vim.opt.mouse = 'nvi'
vim.opt.ignorecase = true
vim.opt.swapfile = false
vim.opt.autochdir = true
vim.opt.conceallevel = 1
vim.opt.termguicolors = true
vim.opt.relativenumber = true
vim.opt.guifont = "JetBrainsMono Nerd Font:h14"
vim.opt.completeopt = { 'menu', 'menuone' }
vim.opt.tabstop=4
vim.opt.shiftwidth=4
vim.opt.expandtab = true
vim.opt.linebreak = true
