
monitor=,preferred,auto,2
$terminal = alacritty
$menu = wofi


exec-once = waybar 



env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24


general {
    gaps_in = 0
    gaps_out = 0

    border_size = 0

    col.active_border = rgb(d8a657) rgba(00ff99ee) 
    col.inactive_border = rgba(595959aa)

    resize_on_border = false

    allow_tearing = false

    layout = scrolling
}
decoration {
    rounding = 0
    # rounding_power = 0
    # active_opacity = 1.0
    # inactive_opacity = 1.0

    shadow {
        enabled = false
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = false
        size = 3
        passes = 1

        vibrancy = 0.1696
    }
}

animations {
    enabled = no

}

misc {
    force_default_wallpaper = 0 
    disable_hyprland_logo = true
}


input {
    kb_layout = us,ru
    kb_variant =
    kb_model =
    kb_options = grp:caps_toggle
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 

    touchpad {
        natural_scroll = false
    }
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

source = keys.conf


windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
  name = apply-hiddify
  match:class = hiddify
  workspace=9
}
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
