return {
    { import = "plugins.tabby" },
    { import = "plugins.dadboard" },
    { import = "plugins.nvim-tree" },
    { import = "plugins.neogit" },
    { import = "plugins.cursorline" },
    { import = "plugins.terminal" },
    { import = "plugins.colorscheme" },
    { import = "plugins.mkdir" },
    { import = "plugins.autosave" },
    { import = "plugins.surround" },
    { import = "plugins.comment" },
    { import = "plugins.lualine" },
    { import = "plugins.vimtex" },
    { import = "plugins.autoclose" },
    { import = "plugins.telescope" },
    { import = "plugins.jaq" },
    { import = "plugins.neoformat" },
    { import = "plugins.cmp-nvim" },
    { import = "plugins.lsp-config" },
    { import = "plugins.treesitter" },
    { import = "plugins.ultisnips" },
}
